// Pure rules of the "Đặc tả" tab (BD SHR0202 Sheet 5 Khu vực F, Sheet 9 mục 5 và 6). No React, no
// i18n: the screen turns the results into red borders, a warning and toasts.
import {
  CONTAINER_KINDS,
  MAX_TYPE_NESTING,
  SCALAR_KINDS,
  type FunctionSignature,
  type ProblemSpec,
  type SpecLanguage,
  type SpecType,
  type TypeKind,
} from "./draft-types";

const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

export const isIdentifier = (value: string) => IDENTIFIER.test(value.trim());

/** A type the author just picked, with the extra fields its kind needs. */
export function defaultType(kind: TypeKind): SpecType {
  if (!CONTAINER_KINDS.includes(kind)) return { kind };
  return kind === "ARRAY"
    ? { kind, of: { kind: "INT" }, dimensions: 1 }
    : { kind, of: { kind: "INT" } };
}

/**
 * Element kinds a container may hold. ARRAY, LINKED_LIST and BINARY_TREE hold a plain value; only LIST
 * may hold another container, and only while the nesting stays within MAX_TYPE_NESTING. `level` is the
 * container's own level, 1 for the outermost.
 */
export function elementKinds(parent: TypeKind, level: number): TypeKind[] {
  if (parent !== "LIST") return SCALAR_KINDS;
  return level < MAX_TYPE_NESTING
    ? [...SCALAR_KINDS, "ARRAY", "LIST", "LINKED_LIST", "BINARY_TREE"]
    : SCALAR_KINDS;
}

export function isTypeValid(type: SpecType, level = 1): boolean {
  if (!CONTAINER_KINDS.includes(type.kind)) return true;
  if (!type.of || !elementKinds(type.kind, level).includes(type.of.kind))
    return false;
  if (
    type.kind === "ARRAY" &&
    !(
      type.dimensions !== undefined &&
      type.dimensions >= 1 &&
      type.dimensions <= 3
    )
  ) {
    return false;
  }
  return isTypeValid(type.of, level + 1);
}

/** True when the signature uses a type the harness schema cannot express (F3-13). */
export function exceedsSchema(spec: ProblemSpec): boolean {
  const { returnType, parameters } = spec.signature;
  return (
    returnType.kind === "OTHER" ||
    parameters.some((parameter) => parameter.type.kind === "OTHER")
  );
}

/** What is wrong with the signature; an empty list means it can drive the harness. */
export function signatureIssues(signature: FunctionSignature): string[] {
  const issues: string[] = [];
  if (!isIdentifier(signature.functionName)) issues.push("functionName");
  if (!isTypeValid(signature.returnType)) issues.push("returnType");
  const seen = new Set<string>();
  for (const parameter of signature.parameters) {
    const name = parameter.name.trim();
    if (!isIdentifier(name)) issues.push(`parameterName:${parameter.id}`);
    else if (seen.has(name)) issues.push(`parameterDuplicate:${parameter.id}`);
    seen.add(name);
    if (!isTypeValid(parameter.type))
      issues.push(`parameterType:${parameter.id}`);
  }
  for (const [language, name] of Object.entries(signature.nameOverrides)) {
    if (name && name.trim() && !isIdentifier(name))
      issues.push(`override:${language}`);
  }
  return issues;
}

/** `UNORDERED_SET` has no meaning for a tree or a linked list (BD Sheet 9 mục 6). */
export function allowsUnorderedSet(spec: ProblemSpec): boolean {
  const kind = spec.signature.returnType.kind;
  return kind !== "BINARY_TREE" && kind !== "LINKED_LIST";
}

export function epsilonValid(spec: ProblemSpec): boolean {
  const value = Number(spec.epsilon);
  return spec.epsilon.trim() !== "" && Number.isFinite(value) && value > 0;
}

export function matchingValid(spec: ProblemSpec): boolean {
  if (spec.matchingStrategy === "EPSILON") return epsilonValid(spec);
  if (spec.matchingStrategy === "UNORDERED_SET")
    return allowsUnorderedSet(spec);
  return true;
}

/**
 * The publish-checklist condition "đã khai đặc tả" (owner 2026-10-03): stdin and stdout formats are
 * written, the matching strategy is valid, and, unless a type falls outside the schema (the problem
 * is then Standard I/O only, F3-13), the shared signature is complete.
 */
export function isSpecComplete(spec: ProblemSpec): boolean {
  if (!spec.stdinFormat.trim() || !spec.stdoutFormat.trim()) return false;
  if (!matchingValid(spec)) return false;
  if (exceedsSchema(spec)) return true;
  return signatureIssues(spec.signature).length === 0;
}

// ---------------------------------------------------------------------------------------------
// Per-language spelling and an illustrative stub. The real starter code is generated by the harness
// (BD architecture/harness.md); this only shows the author what the shared signature turns into.
// ---------------------------------------------------------------------------------------------

function words(name: string): string[] {
  return name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((word) => word.toLowerCase());
}

/** The spelling the system derives: snake_case for Python, camelCase for Java and C++. */
export function derivedName(name: string, language: SpecLanguage): string {
  const parts = words(name);
  if (parts.length === 0) return "";
  if (language === "python") return parts.join("_");
  return (
    parts[0] +
    parts
      .slice(1)
      .map((part) => part[0]!.toUpperCase() + part.slice(1))
      .join("")
  );
}

/** The name used for one language: the override when written, otherwise the derived spelling. */
export function languageName(
  signature: FunctionSignature,
  language: SpecLanguage,
): string {
  const override = signature.nameOverrides[language]?.trim();
  return override || derivedName(signature.functionName, language);
}

const JAVA_BOXED: Record<string, string> = {
  INT: "Integer",
  LONG: "Long",
  DOUBLE: "Double",
  BOOLEAN: "Boolean",
  CHAR: "Character",
  STRING: "String",
};

const SCALAR: Record<SpecLanguage, Record<string, string>> = {
  java: {
    INT: "int",
    LONG: "long",
    DOUBLE: "double",
    BOOLEAN: "boolean",
    CHAR: "char",
    STRING: "String",
  },
  cpp: {
    INT: "int",
    LONG: "long long",
    DOUBLE: "double",
    BOOLEAN: "bool",
    CHAR: "char",
    STRING: "string",
  },
  python: {
    INT: "int",
    LONG: "int",
    DOUBLE: "float",
    BOOLEAN: "bool",
    CHAR: "str",
    STRING: "str",
  },
};

/** `boxed`: inside Java generics a scalar must be its wrapper class (`List<Integer>`, never `List<int>`). */
function typeText(
  type: SpecType,
  language: SpecLanguage,
  boxed = false,
): string {
  const inner = (of: SpecType | undefined, asBoxed: boolean) =>
    of ? typeText(of, language, asBoxed) : "?";
  switch (type.kind) {
    case "ARRAY": {
      const depth = type.dimensions ?? 1;
      const element = inner(type.of, false);
      if (language === "java") return element + "[]".repeat(depth);
      if (language === "cpp")
        return "vector<".repeat(depth) + element + ">".repeat(depth);
      return "List[".repeat(depth) + element + "]".repeat(depth);
    }
    case "LIST":
      if (language === "java") return `List<${inner(type.of, true)}>`;
      return language === "cpp"
        ? `vector<${inner(type.of, false)}>`
        : `List[${inner(type.of, false)}]`;
    case "LINKED_LIST":
      return language === "java"
        ? "ListNode"
        : language === "cpp"
          ? "ListNode*"
          : "Optional[ListNode]";
    case "BINARY_TREE":
      return language === "java"
        ? "TreeNode"
        : language === "cpp"
          ? "TreeNode*"
          : "Optional[TreeNode]";
    case "OTHER":
      return "?";
    default:
      return language === "java" && boxed
        ? JAVA_BOXED[type.kind]!
        : SCALAR[language][type.kind]!;
  }
}

/** One line showing the signature in a language, e.g. `def min_window(s: str, t: str) -> str:`. */
export function renderSignature(
  signature: FunctionSignature,
  language: SpecLanguage,
): string {
  const name = languageName(signature, language) || "?";
  const parameters = signature.parameters;
  const returns = typeText(signature.returnType, language);
  if (language === "python") {
    const list = parameters
      .map((row) => `${row.name || "?"}: ${typeText(row.type, language)}`)
      .join(", ");
    return `def ${name}(${list}) -> ${returns}:`;
  }
  const list = parameters
    .map((row) => `${typeText(row.type, language)} ${row.name || "?"}`)
    .join(", ");
  return language === "java"
    ? `public ${returns} ${name}(${list})`
    : `${returns} ${name}(${list})`;
}
