'use client'

import { useState } from 'react'
import { Activity, BarChart3, Bell, BookOpen, Boxes, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Code2, Download, Gauge, Grid2X2, LayoutDashboard, Menu, Moon, MoreHorizontal, PanelLeft, Search, Settings, ShieldCheck, Sparkles, Sun, Users, X } from 'lucide-react'
import './globals.css'

type NavItem = { label: string; icon: typeof LayoutDashboard }
const nav: NavItem[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Users', icon: Users }, { label: 'Problem library', icon: BookOpen }, { label: 'Submissions', icon: Code2 }, { label: 'Contests', icon: Boxes }, { label: 'Analytics', icon: BarChart3 },
]
const bars = [42, 58, 52, 74, 66, 82, 64, 92, 70, 84, 76, 98, 72, 88, 62, 78, 92, 68, 84, 72, 96, 78, 90, 80]
const activity = [{ name: 'Lê Minh Anh', action: 'completed Two Sum', time: '2m ago', color: 'cyan' }, { name: 'Nguyễn Gia Hân', action: 'submitted a solution', time: '11m ago', color: 'purple' }, { name: 'Trần Quốc Bảo', action: 'joined the platform', time: '24m ago', color: 'orange' }, { name: 'Phạm Hoàng Long', action: 'completed Graph Basics', time: '38m ago', color: 'blue' }]

function Sidebar({ collapsed, setCollapsed, open, setOpen }: { collapsed: boolean; setCollapsed: (v: boolean) => void; open: boolean; setOpen: (v: boolean) => void }) {
  return <aside className={`sidebar ${collapsed ? 'collapsed' : ''} ${open ? 'mobile-open' : ''}`}>
    <div className="brand"><div className="brand-mark"><Sparkles size={16} /></div><span>AlgoPrep</span><button className="mobile-close" onClick={() => setOpen(false)}><X size={18} /></button></div>
    <div className="workspace"><span className="workspace-dot" /> Admin workspace <ChevronDown size={14} /></div>
    <nav className="nav"><p className="eyebrow">Workspace</p>{nav.map(({ label, icon: Icon }) => <button key={label} className={`nav-item ${label === 'Overview' ? 'active' : ''}`}><Icon size={18} /><span>{label}</span>{label === 'Users' && <em>12</em>}</button>)}<p className="eyebrow second">Manage</p><button className="nav-item"><ShieldCheck size={18} /><span>Moderation</span></button><button className="nav-item"><Settings size={18} /><span>Settings</span></button></nav>
    <div className="sidebar-bottom"><div className="pro-card"><div className="pro-icon"><Gauge size={17} /></div><div><strong>Pro workspace</strong><small>All systems operational</small></div></div><button className="profile"><div className="avatar">PS</div><div><strong>Pauline Seitz</strong><small>Administrator</small></div><MoreHorizontal size={16} /></button></div>
    <button className="collapse" onClick={() => setCollapsed(!collapsed)}>{collapsed ? <ChevronRight size={17} /> : <ChevronLeft size={17} />}<span>{collapsed ? 'Expand' : 'Collapse'}</span></button>
  </aside>
}

function Topbar({ onMenu, range, setRange }: { onMenu: () => void; range: string; setRange: (v: string) => void }) {
  return <header className="topbar"><button className="menu-button" onClick={onMenu}><Menu size={20} /></button><div className="search"><Search size={17} /><input aria-label="Search" placeholder="Search anything..." /></div><div className="top-actions"><button aria-label="Help"><CircleHelp size={19} /></button><button aria-label="Notifications" className="notify"><Bell size={19} /><i /></button><div className="divider" /><div className="date-select"><span>Period</span><select value={range} onChange={e => setRange(e.target.value)} aria-label="Period"><option>Last 7 days</option><option>Last 30 days</option><option>This year</option></select></div><div className="top-avatar">PS</div></div></header>
}

function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }
function CardHead({ title, detail }: { title: string; detail?: string }) { return <div className="card-head"><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div><button className="more" aria-label={`${title} options`}><MoreHorizontal size={18} /></button></div> }

export default function Home() {
  const [collapsed, setCollapsed] = useState(false); const [open, setOpen] = useState(false); const [range, setRange] = useState('Last 7 days'); const [dark, setDark] = useState(true)
  return <div className={dark ? 'app' : 'app light'}><Sidebar {...{ collapsed, setCollapsed, open, setOpen }} /><div className="main"><Topbar onMenu={() => setOpen(true)} {...{ range, setRange }} /><main className="content"><div className="welcome"><div><p className="kicker">MONDAY, AUGUST 24, 2026</p><h1>Good morning, Pauline <span>✦</span></h1><p className="subhead">Here&apos;s what&apos;s happening across your learning platform.</p></div><div className="welcome-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Sun size={18} /> : <Moon size={18} />}</button><button className="export"><Download size={16} /> Export report</button></div></div>
      <div className="metrics"><Card className="metric"><div className="metric-icon cyan-bg"><Users size={18} /></div><div className="metric-copy"><span>Total learners</span><strong>8,942</strong><small className="up">↑ 12.8% <b>vs last week</b></small></div><div className="sparkline cyan-line" /></Card><Card className="metric"><div className="metric-icon violet-bg"><Code2 size={18} /></div><div className="metric-copy"><span>Submissions</span><strong>24,681</strong><small className="up">↑ 8.4% <b>vs last week</b></small></div><div className="sparkline violet-line" /></Card><Card className="metric"><div className="metric-icon orange-bg"><BarChart3 size={18} /></div><div className="metric-copy"><span>Problems solved</span><strong>18,307</strong><small className="down">↓ 2.1% <b>vs last week</b></small></div><div className="sparkline orange-line" /></Card><Card className="metric"><div className="metric-icon green-bg"><Activity size={18} /></div><div className="metric-copy"><span>Avg. completion</span><strong>72.4%</strong><small className="up">↑ 4.6% <b>vs last week</b></small></div><div className="sparkline green-line" /></Card></div>
      <div className="grid-main"><Card className="chart-card"><CardHead title="Learning activity" detail="Daily active learners and submissions" /><div className="legend"><span><i className="dot cyan" /> Active learners</span><span><i className="dot violet" /> Submissions</span><div className="chart-range"><button className="selected">7D</button><button>30D</button><button>3M</button></div></div><div className="bar-chart">{bars.map((height, i) => <div className="bar-group" key={i}><div className="bar violet-bar" style={{ height: `${height * .68}%` }} /><div className="bar cyan-bar" style={{ height: `${height}%` }} />{i % 4 === 0 && <label>{['Mon','Tue','Wed','Thu','Fri','Sat'][i / 4]}</label>}</div>)}</div></Card><Card className="activity-card"><CardHead title="Recent activity" detail="Latest platform events" /><div className="activity-list">{activity.map(item => <div className="activity-row" key={item.name}><div className={`activity-avatar ${item.color}`}>{item.name.split(' ').map(v => v[0]).join('').slice(0,2)}</div><div><strong>{item.name}</strong><p>{item.action}</p></div><time>{item.time}</time></div>)}</div><button className="view-all">View all activity <ChevronRight size={15} /></button></Card></div>
      <div className="grid-bottom"><Card><CardHead title="Problem difficulty" detail="Across 214 active problems" /><div className="difficulty"><div className="ring"><div><strong>68%</strong><span>completion</span></div></div><div className="difficulty-list"><div><span><i className="dot green" /> Easy</span><strong>92 <small>43%</small></strong></div><div><span><i className="dot cyan" /> Medium</span><strong>84 <small>39%</small></strong></div><div><span><i className="dot orange" /> Hard</span><strong>38 <small>18%</small></strong></div></div></div></Card><Card><CardHead title="Submission status" detail="Last 7 days" /><div className="status"><div className="status-number"><strong>81.6%</strong><span>accepted rate</span><div className="progress"><i /></div></div><div className="status-stats"><div><i className="dot green" /><span>Accepted</span><strong>20,128</strong></div><div><i className="dot red" /><span>Rejected</span><strong>4,553</strong></div></div></div></Card><Card className="health-card"><CardHead title="System health" detail="All services operational" /><div className="health-score"><div className="health-ring"><strong>99.9</strong><span>uptime</span></div><div className="health-bars">{['API gateway','Judge service','Database'].map((x, i) => <div key={x}><span>{x}</span><i><b style={{ width: `${[99, 97, 100][i]}%` }} /></i><small>Operational</small></div>)}</div></div></Card></div>
    </main></div></div>
}
