// PROTOTYPE — no DD yet. See 06-plan/PROTOTYPE_DEBT.md section 9.
export type {
  ClassAssignmentGroup,
  ClassAssignmentItem,
  Difficulty,
  InProgressProblem,
  InputMethod,
  OverallVerdict,
  ProblemCatalogSummary,
  ProblemDetail,
  ProblemExample,
  ProblemListFilter,
  ProblemListItem,
  ProblemListPage,
  RatioStat,
  SampleRunResult,
  SavedProblem,
  SolutionReviewQuickInsight,
  SolveState,
  StarterCodeKey,
  SubmissionHistoryItem,
  SubmissionLanguage,
  SubmissionModel,
  SubmissionRunResult,
  TestcaseVerdict,
  TopicProgress,
  WrapperMode,
} from "./model/types";
export {
  fetchProblemDetail,
  fetchProblemListPage,
  fetchSavedProblems,
  simulateSubmission,
} from "./api/__mock__/problem-mocks";
export {
  AI_GUARD_KEYS,
  TESTCASE_CATEGORIES,
  type AiGuardKey,
  type DroppedReason,
  type GenerateTestcasesInput,
  type GenerateTestcasesResult,
  type ProblemDraft,
  type ProblemDraftRecord,
  type ProblemLimits,
  type Testcase,
  type TestcaseCategory,
  type TestcaseOrigin,
  type TestcaseVisibility,
  type WorkedExample,
} from "./model/draft-types";
export {
  useGenerateTestcases,
  useProblemDraft,
  usePublishProblem,
  useSaveProblemDraft,
} from "./api/queries";
export {
  addProblemTopic,
  problemTopicLabel,
  moveProblemTopic,
  removeProblemTopic,
  renameProblemTopic,
  useProblemTopics,
  type ProblemTopic,
} from "./model/topic-store";
export {
  addProblemLevel,
  moveProblemLevel,
  problemLevelLabel,
  problemLevelRank,
  problemLevelTone,
  removeProblemLevel,
  renameProblemLevel,
  useProblemLevels,
  type ProblemLevel,
  type ProblemLevelError,
} from "./model/level-store";
export {
  AI_GENERATION_LIMIT_MAX,
  AI_GENERATION_LIMIT_MIN,
  aiGenerationSettings,
} from "./model/generation-settings-store";
export { canViewerSeeProblem } from "./model/mock-ownership";
export {
  allowsUnorderedSet,
  defaultType,
  derivedName,
  elementKinds,
  epsilonValid,
  exceedsSchema,
  isIdentifier,
  isSpecComplete,
  isTypeValid,
  languageName,
  matchingValid,
  renderSignature,
  signatureIssues,
} from "./model/spec";
export {
  CONTAINER_KINDS,
  MAX_TYPE_NESTING,
  MATCHING_STRATEGIES,
  SCALAR_KINDS,
  SPEC_LANGUAGES,
  TYPE_KINDS,
  type FunctionSignature,
  type MatchingStrategy,
  type ProblemSpec,
  type ScalarKind,
  type SpecLanguage,
  type SpecParameter,
  type SpecType,
  type TypeKind,
} from "./model/draft-types";
