// PROTOTYPE — no DD yet. See 06-plan/PROTOTYPE_DEBT.md section 9.
export type {
  ClassAssignmentGroup,
  ClassAssignmentItem,
  Difficulty,
  InProgressProblem,
  InputMethod,
  OverallVerdict,
  ProblemCatalogSummary,
  ProblemDetail,
  ProblemExample,
  ProblemListFilter,
  ProblemListItem,
  ProblemListPage,
  RatioStat,
  SampleRunResult,
  SavedProblem,
  SolutionReviewQuickInsight,
  SolveState,
  StarterCodeKey,
  SubmissionHistoryItem,
  SubmissionLanguage,
  SubmissionModel,
  SubmissionRunResult,
  TestcaseVerdict,
  TopicProgress,
  WrapperMode,
} from "./model/types";
export {
  fetchProblemDetail,
  fetchProblemListPage,
  fetchSavedProblems,
  simulateSubmission,
} from "./api/__mock__/problem-mocks";
