// PROTOTYPE — no DD yet. See 06-plan/PROTOTYPE_DEBT.md section 9.
export type {
  ClassAssignmentGroup,
  ClassAssignmentItem,
  Difficulty,
  InProgressProblem,
  InputMethod,
  OverallVerdict,
  ProblemCatalogSummary,
  ProblemDetail,
  ProblemExample,
  ProblemListFilter,
  ProblemListItem,
  ProblemListPage,
  RatioStat,
  SampleRunResult,
  SavedProblem,
  SolutionReviewQuickInsight,
  SolveState,
  StarterCodeKey,
  SubmissionHistoryItem,
  SubmissionLanguage,
  SubmissionModel,
  SubmissionRunResult,
  TestcaseVerdict,
  TopicProgress,
  WrapperMode,
} from "./model/types";
export {
  fetchProblemDetail,
  fetchProblemListPage,
  fetchSavedProblems,
  simulateSubmission,
} from "./api/__mock__/problem-mocks";
export {
  AI_GUARD_KEYS,
  TESTCASE_CATEGORIES,
  type AiGuardKey,
  type DroppedReason,
  type GenerateTestcasesInput,
  type GenerateTestcasesResult,
  type ProblemDraft,
  type ProblemDraftRecord,
  type ProblemLimits,
  type Testcase,
  type TestcaseCategory,
  type TestcaseOrigin,
  type TestcaseVisibility,
  type WorkedExample,
} from "./model/draft-types";
export {
  useGenerateTestcases,
  useProblemDraft,
  usePublishProblem,
  useSaveProblemDraft,
} from "./api/queries";
export {
  addProblemTopic,
  problemTopicLabel,
  removeProblemTopic,
  renameProblemTopic,
  useProblemTopics,
  type ProblemTopic,
} from "./model/topic-store";
